# Generated by Django 3.2.12 on 2022-02-06 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220206_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='old_resume',
        ),
        migrations.AddField(
            model_name='user',
            name='all_resume',
            field=models.ManyToManyField(related_name='all_resume', to='users.Resume'),
        ),
    ]
